import { DailyNewsReport } from '@/lib/types';
import { SpecialEditionReport } from '@/lib/specialEditionTypes';

export function generateDailyNewsHtml(report: DailyNewsReport, preferredLanguage?: 'en' | 'de', logoSrc?: string): string {
  const lang = preferredLanguage || (report.language === 'de' ? 'de' : 'en');
  const labels = lang === 'de'
    ? {
        generated: 'Erstellt', sources: 'Quellen', sourceComparison: 'Quellenvergleich',
        criticalCommentary: 'Kritischer Kommentar', mondcivitanReflection: 'Mondcivitan-Reflexion',
        ethicalPrefix: 'Ethische Betrachtung', conclusion: 'Fazit', readArticle: '[Artikel lesen]',
        footer1: 'Dieser Bericht wurde durch die NewsFriend KI-Analyse erstellt.',
        footer2: 'Überprüfen Sie wichtige Informationen immer anhand von Primärquellen.',
      }
    : {
        generated: 'Generated', sources: 'Sources', sourceComparison: 'Source Comparison',
        criticalCommentary: 'Critical Commentary', mondcivitanReflection: 'Mondcivitan Reflection',
        ethicalPrefix: 'Ethical Consideration', conclusion: 'Conclusion', readArticle: '[Read Article]',
        footer1: 'This report was generated by NewsFriend AI analysis.',
        footer2: 'Always verify critical information from primary sources.',
      };

  const generatedAtLabel = new Date(report.generatedAt).toLocaleString(lang === 'de' ? 'de-DE' : 'en-GB', { timeZone: 'UTC', timeZoneName: 'short' });
  const significanceColor: Record<string, string> = { high: '#ef4444', medium: '#f59e0b', low: '#6b7280' };
  const themes = Array.isArray(report.themes) ? report.themes : [];
  const sourcesAnalyzed = Array.isArray(report.sourcesAnalyzed) ? report.sourcesAnalyzed : [];

  // Legacy field map for old report format
  const LEGACY_FIELDS: { key: string; name: string; icon: string; bg: string; border: string; heading: string; text: string }[] = [
    { key: 'schweitzerEthical', name: 'Albert Schweitzer', icon: '🌿', bg: '#ecfdf5', border: '#a7f3d0', heading: '#065f46', text: '#064e3b' },
    { key: 'ethicalJesus', name: 'Jesus of Nazareth', icon: '✝', bg: '#f0f9ff', border: '#bae6fd', heading: '#0c4a6e', text: '#0c4a6e' },
    { key: 'ethicalCovey', name: 'Stephen R. Covey', icon: '🧭', bg: '#eef2ff', border: '#c7d2fe', heading: '#3730a3', text: '#312e81' },
    { key: 'ethicalGandhi', name: 'Mahatma Gandhi', icon: '☸', bg: '#fff7ed', border: '#fed7aa', heading: '#9a3412', text: '#7c2d12' },
    { key: 'ethicalBuddha', name: 'Buddha', icon: '🪷', bg: '#fefce8', border: '#fde68a', heading: '#854d0e', text: '#713f12' },
    { key: 'ethicalMohammed', name: 'Prophet Mohammed', icon: '☪', bg: '#f0fdfa', border: '#99f6e4', heading: '#134e4a', text: '#115e59' },
    { key: 'ethicalTorah', name: 'Torah', icon: '✡', bg: '#f5f3ff', border: '#c4b5fd', heading: '#5b21b6', text: '#4c1d95' },
    { key: 'ethicalOshi', name: 'Oshi', icon: '⛩', bg: '#fff1f2', border: '#fecdd3', heading: '#9f1239', text: '#881337' },
    { key: 'ethicalRajneesh', name: 'Bhagwan Shree Rajneesh', icon: '🪷', bg: '#fdf4ff', border: '#f0abfc', heading: '#86198f', text: '#701a75' },
    { key: 'ethicalGita', name: 'Bhagavad Gita', icon: '🙏', bg: '#fffbeb', border: '#fcd34d', heading: '#92400e', text: '#78350f' },
  ];

  // Build ethical sections from new or legacy format
  let ethicalHtml = '';
  if (Array.isArray((report as any).ethicalConsiderations)) {
    for (const ec of (report as any).ethicalConsiderations) {
      ethicalHtml += `
      <section style="background:${escapeHtml(ec.colorBg || '#f3f4f6')};border:1px solid ${escapeHtml(ec.colorBorder || '#e5e7eb')};border-radius:8px;padding:24px;margin-top:16px;">
        <h2 style="font-size:18px;font-weight:700;margin:0 0 12px 0;color:${escapeHtml(ec.colorHeading || '#111')};">${escapeHtml(ec.icon || '🌿')} ${labels.ethicalPrefix} — ${escapeHtml(ec.perspectiveName)}</h2>
        <p style="line-height:1.7;white-space:pre-line;margin:0;color:${escapeHtml(ec.colorText || '#333')};">${escapeHtml(ec.content)}</p>
      </section>`;
    }
  } else {
    for (const f of LEGACY_FIELDS) {
      const content = (report as any)[f.key];
      if (content) {
        ethicalHtml += `
      <section style="background:${f.bg};border:1px solid ${f.border};border-radius:8px;padding:24px;margin-top:16px;">
        <h2 style="font-size:18px;font-weight:700;margin:0 0 12px 0;color:${f.heading};">${f.icon} ${labels.ethicalPrefix} — ${escapeHtml(f.name)}</h2>
        <p style="line-height:1.7;white-space:pre-line;margin:0;color:${f.text};">${escapeHtml(content)}</p>
      </section>`;
      }
    }
  }

  const themesHtml = themes.map((theme, index) => {
    const sourceAnalysisHtml = (theme.sourceAnalysis || []).map((sa) => {
      const quotesHtml = (sa.keyQuotes || []).map((q) => `<blockquote style="margin:4px 0;padding-left:10px;border-left:2px solid #d1d5db;font-style:italic;color:#6b7280;font-size:14px;">"${escapeHtml(q)}"</blockquote>`).join('');
      const biasHtml = (sa.biasIndicators || []).map((b) => `<span style="display:inline-block;padding:2px 8px;margin:2px;border:1px solid #d1d5db;border-radius:12px;font-size:12px;color:#6b7280;">${escapeHtml(b)}</span>`).join('');
      const linkHtml = sa.articleUrl ? ` <a href="${escapeHtml(sa.articleUrl)}" target="_blank" style="font-size:12px;color:#3b82f6;">${labels.readArticle}</a>` : '';
      return `<div style="padding-left:16px;border-left:2px solid rgba(59,130,246,0.3);margin-bottom:12px;">
        <div><strong style="font-size:14px;">${escapeHtml(sa.sourceName)}</strong>${linkHtml}</div>
        <p style="font-size:14px;color:#6b7280;margin:4px 0;">${escapeHtml(sa.stance)}</p>
        ${quotesHtml}${biasHtml ? `<div style="margin-top:6px;">${biasHtml}</div>` : ''}
      </div>`;
    }).join('');

    return `<article style="margin-bottom:40px;">
      <header style="margin-bottom:16px;">
        <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:16px;">
          <h2 style="font-size:20px;font-weight:700;margin:0;line-height:1.3;"><span style="color:#3b82f6;margin-right:8px;">${index + 1}.</span>${escapeHtml(theme.headline)}</h2>
          <span style="display:inline-block;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:600;color:white;background:${significanceColor[theme.significance] || '#6b7280'};white-space:nowrap;">${escapeHtml(theme.significance)}</span>
        </div>
        <p style="margin-top:8px;color:#6b7280;line-height:1.6;">${escapeHtml(theme.summary)}</p>
      </header>
      <div style="background:#f9fafb;border-radius:8px;padding:16px;margin-bottom:16px;">
        <h3 style="font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#9ca3af;margin:0 0 12px 0;">${labels.sourceComparison}</h3>
        ${sourceAnalysisHtml}
      </div>
      <div style="background:#eff6ff;border-radius:8px;padding:16px;">
        <h3 style="font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#3b82f6;margin:0 0 8px 0;">${labels.criticalCommentary}</h3>
        <p style="font-size:14px;line-height:1.6;margin:0;">${escapeHtml(theme.criticalCommentary)}</p>
      </div>
      ${theme.mondcivitanReflection ? `<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:16px;margin-top:12px;">
        <h3 style="font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#b45309;margin:0 0 8px 0;">☮ ${labels.mondcivitanReflection}</h3>
        <p style="font-size:14px;line-height:1.6;margin:0;color:#78350f;">${escapeHtml(theme.mondcivitanReflection)}</p>
      </div>` : ''}
      ${index < themes.length - 1 ? '<hr style="margin-top:32px;border:none;border-top:1px solid #e5e7eb;">' : ''}
    </article>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(report.title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 32px; background: #fff; color: #111; max-width: 900px; margin: 0 auto; line-height: 1.5; }
  a { color: #3b82f6; text-decoration: none; }
  a:hover { text-decoration: underline; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <header style="text-align:center;margin-bottom:24px;padding-bottom:24px;border-bottom:2px solid #3b82f6;">
    <div style="margin-bottom:12px;">
      <a href="https://newsfriend.org" target="_blank" rel="noopener noreferrer" style="display:inline-block;">
        <img src="${logoSrc || 'https://newsfriend.org/logo.jpg'}" alt="NewsFriend" style="height:48px;width:auto;max-width:200px;" />
      </a>
    </div>
    <h1 style="font-size:28px;font-weight:700;margin:0 0 8px 0;">${escapeHtml(report.title)}</h1>
    ${(report as any).bannerImageUrl ? `<div style="max-width:900px;margin:16px auto;"><img src="${escapeHtml((report as any).bannerImageUrl)}" alt="" style="width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:8px;display:block;" /></div>` : ''}
    <p style="font-size:14px;color:#6b7280;margin:0;">${labels.generated} ${generatedAtLabel} • ${labels.sources}: ${escapeHtml(sourcesAnalyzed.join(', '))}</p>
  </header>
  <section style="margin-bottom:32px;">
    <p style="line-height:1.7;white-space:pre-line;">${escapeHtml(report.introduction)}</p>
  </section>
  <hr style="margin:32px 0;border:none;border-top:1px solid #e5e7eb;">
  ${themesHtml}
  <hr style="margin:32px 0;border:none;border-top:1px solid #e5e7eb;">
  <section style="background:#f3f4f6;border-radius:8px;padding:24px;">
    <h2 style="font-size:18px;font-weight:700;margin:0 0 12px 0;">${labels.conclusion}</h2>
    <p style="line-height:1.7;white-space:pre-line;margin:0;">${escapeHtml(report.conclusion)}</p>
  </section>
  ${ethicalHtml}
  <footer style="margin-top:32px;padding-top:24px;border-top:1px solid #e5e7eb;text-align:center;font-size:14px;color:#9ca3af;">
    <p>${labels.footer1}</p>
    <p>${labels.footer2}</p>
  </footer>
</body>
</html>`;
}

function escapeHtml(value: unknown): string {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function openReportInNewTab(html: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  // Anchor click in the same user gesture is the most reliable way to open
  // a new tab without being treated as a popup by browsers.
  const a = document.createElement('a');
  a.href = url;
  a.target = '_blank';
  a.rel = 'noopener noreferrer';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Keep the blob alive long enough for the new tab to load it
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

export function generateSpecialEditionHtml(report: SpecialEditionReport, preferredLanguage?: 'en' | 'de', logoSrc?: string): string {
  const lang = preferredLanguage || (report.language === 'de' ? 'de' : 'en');
  const labels = lang === 'de'
    ? {
        badge: 'Sonderausgabe', topic: 'Thema', generated: 'Erstellt', sources: 'Quellen',
        summary: 'Zusammenfassung', discussion: 'Diskussion', sourceComparison: 'Quellenvergleich',
        criticalCommentary: 'Kritischer Kommentar', mondcivitanReflection: 'Mondcivitan-Reflexion',
        actionSteps: 'Was können wir tun?', conclusion: 'Fazit', readArticle: '[Artikel lesen]',
        footer1: 'Dieser Bericht wurde durch die NewsFriend KI-Analyse erstellt.',
        footer2: 'Überprüfen Sie wichtige Informationen immer anhand von Primärquellen.',
      }
    : {
        badge: 'Special Edition', topic: 'Topic', generated: 'Generated', sources: 'Sources',
        summary: 'Summary', discussion: 'Discussion', sourceComparison: 'Source Comparison',
        criticalCommentary: 'Critical Commentary', mondcivitanReflection: 'Mondcivitan Reflection',
        actionSteps: 'What can we do?', conclusion: 'Conclusion', readArticle: '[Read Article]',
        footer1: 'This report was generated by NewsFriend AI analysis.',
        footer2: 'Always verify critical information from primary sources.',
      };

  const generatedAtLabel = new Date(report.generatedAt).toLocaleString(lang === 'de' ? 'de-DE' : 'en-GB', { timeZone: 'UTC', timeZoneName: 'short' });

  const sourceAnalysisHtml = (report.sourceAnalysis || []).map((sa) => {
    const quotesHtml = (sa.keyQuotes || []).map((q) => `<blockquote style="margin:4px 0;padding-left:10px;border-left:2px solid #d1d5db;font-style:italic;color:#6b7280;font-size:14px;">"${escapeHtml(q)}"</blockquote>`).join('');
    const biasHtml = (sa.biasIndicators || []).map((b) => `<span style="display:inline-block;padding:2px 8px;margin:2px;border:1px solid #d1d5db;border-radius:12px;font-size:12px;color:#6b7280;">${escapeHtml(b)}</span>`).join('');
    const linkHtml = sa.articleUrl ? ` <a href="${escapeHtml(sa.articleUrl)}" target="_blank" style="font-size:12px;color:#3b82f6;">${labels.readArticle}</a>` : '';
    return `<div style="padding-left:16px;border-left:2px solid rgba(245,158,11,0.4);margin-bottom:12px;">
      <div><strong style="font-size:14px;">${escapeHtml(sa.sourceName)}</strong>${linkHtml}</div>
      <p style="font-size:14px;color:#6b7280;margin:4px 0;">${escapeHtml(sa.stance)}</p>
      ${quotesHtml}${biasHtml ? `<div style="margin-top:6px;">${biasHtml}</div>` : ''}
    </div>`;
  }).join('');

  const cleanedSteps = (report.actionSteps || []).map(stripLeadingNumber);
  const stepsHtml = cleanedSteps.length > 0 ? `
  <section style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:8px;padding:24px;margin-bottom:32px;">
    <h2 style="font-size:18px;font-weight:700;margin:0 0 12px 0;color:#047857;">💡 ${labels.actionSteps}</h2>
    <ol style="margin:0;padding-left:24px;color:#064e3b;line-height:1.7;">
      ${cleanedSteps.map((s) => `<li style="margin-bottom:6px;">${escapeHtml(s)}</li>`).join('')}
    </ol>
  </section>` : '';

  const mondcivitanHtml = report.mondcivitanReflection ? `
  <section style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:24px;margin-bottom:32px;">
    <h2 style="font-size:18px;font-weight:700;margin:0 0 12px 0;color:#b45309;">☮ ${labels.mondcivitanReflection}</h2>
    <p style="line-height:1.7;white-space:pre-line;margin:0;color:#78350f;">${escapeHtml(report.mondcivitanReflection)}</p>
  </section>` : '';

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(report.headline)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0 auto; padding: 32px; background: #fff; color: #111; max-width: 900px; line-height: 1.5; }
  a { color: #3b82f6; text-decoration: none; }
  a:hover { text-decoration: underline; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  ${(report as any).bannerImageUrl ? `<div style="max-width:900px;margin:0 auto 24px;"><img src="${escapeHtml((report as any).bannerImageUrl)}" alt="" style="width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:8px;display:block;" /></div>` : ''}
  <header style="text-align:center;margin-bottom:32px;padding-bottom:24px;border-bottom:2px solid #f59e0b;">
    <div style="margin-bottom:12px;">
      <a href="https://newsfriend.org" target="_blank" rel="noopener noreferrer" style="display:inline-block;">
        <img src="${logoSrc || 'https://newsfriend.org/logo.jpg'}" alt="NewsFriend" style="height:48px;width:auto;max-width:200px;" />
      </a>
    </div>
    <div style="display:inline-block;background:#f59e0b;color:#fff;padding:4px 12px;border-radius:9999px;font-size:12px;font-weight:600;margin-bottom:12px;">★ ${labels.badge}</div>
    <h1 style="font-size:28px;font-weight:700;margin:0 0 8px 0;">${escapeHtml(report.headline)}</h1>
    <p style="font-size:15px;color:#6b7280;font-style:italic;margin:0 0 8px 0;">${labels.topic}: ${escapeHtml(report.topic)}</p>
    <p style="font-size:14px;color:#6b7280;margin:0;">${labels.generated} ${generatedAtLabel} • ${labels.sources}: ${escapeHtml(report.sourcesAnalyzed.join(', '))}</p>
  </header>

  <section style="margin-bottom:32px;">
    <h2 style="font-size:20px;font-weight:700;margin:0 0 12px 0;">${labels.summary}</h2>
    <p style="line-height:1.7;white-space:pre-line;margin:0;">${escapeHtml(report.summary)}</p>
  </section>

  <hr style="margin:32px 0;border:none;border-top:1px solid #e5e7eb;">

  <section style="margin-bottom:32px;">
    <h2 style="font-size:20px;font-weight:700;margin:0 0 16px 0;">${labels.discussion}</h2>
    <p style="line-height:1.7;white-space:pre-line;margin:0 0 24px 0;">${escapeHtml(report.discussion)}</p>
    <div style="background:#f9fafb;border-radius:8px;padding:16px;">
      <h3 style="font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;color:#9ca3af;margin:0 0 12px 0;">${labels.sourceComparison}</h3>
      ${sourceAnalysisHtml}
    </div>
  </section>

  <section style="background:#eff6ff;border-radius:8px;padding:24px;margin-bottom:32px;">
    <h2 style="font-size:18px;font-weight:700;margin:0 0 12px 0;color:#3b82f6;text-transform:uppercase;letter-spacing:0.05em;">${labels.criticalCommentary}</h2>
    <p style="line-height:1.7;white-space:pre-line;margin:0;">${escapeHtml(report.criticalCommentary)}</p>
  </section>

  ${mondcivitanHtml}
  ${stepsHtml}

  <hr style="margin:32px 0;border:none;border-top:1px solid #e5e7eb;">

  <section style="background:#f3f4f6;border-radius:8px;padding:24px;">
    <h2 style="font-size:18px;font-weight:700;margin:0 0 12px 0;">${labels.conclusion}</h2>
    <p style="line-height:1.7;white-space:pre-line;margin:0;">${escapeHtml(report.conclusion)}</p>
  </section>

  <footer style="margin-top:32px;padding-top:24px;border-top:1px solid #e5e7eb;text-align:center;font-size:14px;color:#9ca3af;">
    <p>${labels.footer1}</p>
    <p>${labels.footer2}</p>
  </footer>
</body>
</html>`;
}

export function stripLeadingNumber(s: string): string {
  return s.replace(/^\s*(?:\d+[.)\]:-]\s*|[•\-*]\s+)/, '').trim();
}

export function downloadReportHtml(html: string, filename: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.html`;
  a.click();
  URL.revokeObjectURL(url);
}
