import { useRef } from 'react';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';
import { ShareButtons } from '@/components/ShareButtons';
import { useLanguage } from '@/lib/i18n/LanguageContext';
import { SpecialEditionReport } from '@/lib/specialEditionTypes';
import { Star, Lightbulb, Download, ExternalLink } from 'lucide-react';
import {
  generateSpecialEditionHtml,
  openReportInNewTab,
  downloadReportHtml,
  stripLeadingNumber,
} from '@/lib/generateReportHtml';
import { getLogoDataUri } from '@/lib/logoDataUri';
import { useBannerSettings } from '@/lib/useBannerSettings';

interface Props {
  report: SpecialEditionReport;
}

// Localized labels keyed off the REPORT's language (not the UI language),
// so a German special edition always reads in German even when the admin
// previews it from an English UI.
function getLabels(lang: 'en' | 'de') {
  return lang === 'de'
    ? {
        badge: 'Sonderausgabe',
        topic: 'Thema',
        generated: 'Erstellt',
        sources: 'Quellen',
        summary: 'Zusammenfassung',
        discussion: 'Diskussion',
        sourceComparison: 'Quellenvergleich',
        readArticle: '[Artikel lesen]',
        criticalCommentary: 'Kritischer Kommentar',
        mondcivitanReflection: 'Mondcivitan-Reflexion',
        actionSteps: 'Was können wir tun?',
        conclusion: 'Fazit',
        footer1: 'Dieser Bericht wurde durch die NewsFriend KI-Analyse erstellt.',
        footer2: 'Überprüfen Sie wichtige Informationen immer anhand von Primärquellen.',
        openNewTab: 'In neuem Tab öffnen',
        downloadHtml: 'HTML herunterladen',
      }
    : {
        badge: 'Special Edition',
        topic: 'Topic',
        generated: 'Generated',
        sources: 'Sources',
        summary: 'Summary',
        discussion: 'Discussion',
        sourceComparison: 'Source Comparison',
        readArticle: '[Read Article]',
        criticalCommentary: 'Critical Commentary',
        mondcivitanReflection: 'Mondcivitan Reflection',
        actionSteps: 'What can we do?',
        conclusion: 'Conclusion',
        footer1: 'This report was generated by NewsFriend AI analysis.',
        footer2: 'Always verify critical information from primary sources.',
        openNewTab: 'Open in New Tab',
        downloadHtml: 'Download HTML',
      };
}

export function SpecialEditionView({ report }: Props) {
  // We deliberately ignore the UI language: the rendered report should always
  // reflect the language it was generated in.
  useLanguage();
  const reportRef = useRef<HTMLDivElement>(null);

  const reportLang: 'en' | 'de' = report.language === 'de' ? 'de' : 'en';
  const L = getLabels(reportLang);

  // Strip any leading "1.", "1)" etc. the model may have included so we don't
  // render duplicate numbering with the visual <ol>-style counter.
  const cleanedSteps = (report.actionSteps || []).map(stripLeadingNumber);
  const bannerSettings = useBannerSettings();
  const showBanner = bannerSettings.special && !!report.bannerImageUrl;

  const handleDownload = async () => {
    const logo = await getLogoDataUri();
    downloadReportHtml(generateSpecialEditionHtml(report, reportLang, logo), `special-edition-${reportLang}`);
  };

  const handleOpenInNewTab = async () => {
    const logo = await getLogoDataUri();
    openReportInNewTab(generateSpecialEditionHtml(report, reportLang, logo));
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-center gap-2">
        <Button onClick={handleOpenInNewTab} variant="outline" className="gap-2">
          <ExternalLink className="h-4 w-4" /> {L.openNewTab}
        </Button>
        <Button onClick={handleDownload} className="gap-2">
          <Download className="h-4 w-4" /> {L.downloadHtml}
        </Button>
      </div>

      <div
        ref={reportRef}
        data-report-content
        className="bg-background text-foreground p-8 max-w-4xl mx-auto px-[20px] py-[20px]"
      >
        {showBanner && (
          <div className="mb-6 -mx-[20px] sm:mx-0 overflow-hidden sm:rounded-lg">
            <img src={report.bannerImageUrl} alt="" className="w-full aspect-[16/9] object-cover" loading="lazy" />
          </div>
        )}
        <header className="text-center mb-8 pb-6 border-b-2 border-amber-500/60">
          <Badge className="mb-3 gap-1 bg-amber-500 hover:bg-amber-500 text-white">
            <Star className="h-3 w-3" /> {L.badge}
          </Badge>
          <h1 className="text-3xl font-bold tracking-tight mb-2">{report.headline}</h1>
          <p className="text-base text-muted-foreground italic mb-2">
            {L.topic}: {report.topic}
          </p>
          <p className="text-sm text-muted-foreground">
            {L.generated}{' '}
            {new Date(report.generatedAt).toLocaleString(reportLang === 'de' ? 'de-DE' : 'en-GB', {
              timeZone: 'UTC',
              timeZoneName: 'short',
            })}{' '}
            • {L.sources}: {report.sourcesAnalyzed.join(', ')}
          </p>
        </header>

        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">{L.summary}</h2>
          <p className="text-base leading-relaxed whitespace-pre-line">{report.summary}</p>
        </section>

        <Separator className="my-8" />

        <section className="mb-8">
          <h2 className="text-xl font-bold mb-4">{L.discussion}</h2>
          <p className="text-base leading-relaxed whitespace-pre-line mb-6">{report.discussion}</p>

          <div className="bg-muted/30 rounded-lg p-4 mb-4">
            <h3 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground mb-3">
              {L.sourceComparison}
            </h3>
            <div className="space-y-4">
              {report.sourceAnalysis.map((sa, i) => (
                <div key={i} className="border-l-2 border-amber-500/40 pl-4">
                  <div className="flex items-center gap-2">
                    <h4 className="font-semibold text-sm">{sa.sourceName}</h4>
                    {sa.articleUrl && (
                      <a
                        href={sa.articleUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary hover:underline"
                      >
                        {L.readArticle}
                      </a>
                    )}
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">{sa.stance}</p>
                  {sa.keyQuotes?.length > 0 && (
                    <div className="mt-2">
                      {sa.keyQuotes.map((q, qi) => (
                        <blockquote
                          key={qi}
                          className="text-sm italic border-l-2 border-muted pl-2 my-1"
                        >
                          "{q}"
                        </blockquote>
                      ))}
                    </div>
                  )}
                  {sa.biasIndicators?.length > 0 && (
                    <div className="mt-2 flex flex-wrap gap-1">
                      {sa.biasIndicators.map((b, bi) => (
                        <Badge key={bi} variant="outline" className="text-xs">
                          {b}
                        </Badge>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="bg-primary/5 rounded-lg p-6 mb-8">
          <h2 className="text-lg font-bold mb-3 text-primary uppercase tracking-wide">
            {L.criticalCommentary}
          </h2>
          <p className="text-base leading-relaxed whitespace-pre-line">{report.criticalCommentary}</p>
        </section>

        {report.mondcivitanReflection && (
          <section className="bg-amber-50 dark:bg-amber-950/30 rounded-lg p-6 mb-8 border border-amber-200 dark:border-amber-800">
            <h2 className="text-lg font-bold mb-3 text-amber-700 dark:text-amber-400">
              ☮ {L.mondcivitanReflection}
            </h2>
            <p className="text-base leading-relaxed text-amber-900 dark:text-amber-200 whitespace-pre-line">
              {report.mondcivitanReflection}
            </p>
          </section>
        )}

        {cleanedSteps.length > 0 && (
          <section className="bg-emerald-50 dark:bg-emerald-950/30 rounded-lg p-6 mb-8 border border-emerald-200 dark:border-emerald-800">
            <h2 className="text-lg font-bold mb-3 text-emerald-700 dark:text-emerald-400 flex items-center gap-2">
              <Lightbulb className="h-5 w-5" /> {L.actionSteps}
            </h2>
            <ul className="space-y-2">
              {cleanedSteps.map((step, i) => (
                <li
                  key={i}
                  className="text-base leading-relaxed text-emerald-900 dark:text-emerald-200 flex gap-2"
                >
                  <span className="font-bold shrink-0">{i + 1}.</span>
                  <span>{step}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        <Separator className="my-8" />
        <section className="bg-muted/50 rounded-lg p-6">
          <h2 className="text-lg font-bold mb-3">{L.conclusion}</h2>
          <p className="text-base leading-relaxed whitespace-pre-line">{report.conclusion}</p>
        </section>

        <footer className="mt-8 pt-6 border-t text-center text-sm text-muted-foreground space-y-3">
          <p>{L.footer1}</p>
          <p>{L.footer2}</p>
          <div className="flex justify-center pt-2">
            <ShareButtons title={report.headline} url="https://newsfriend.org" />
          </div>
        </footer>
      </div>
    </div>
  );
}
